apiVersion: v2
name: langflow-ide
description: Helm chart for Langflow IDE
type: application
version: 0.1.1
appVersion: v1.2.0
maintainers:
  - name: Langflow
    email: contact@langflow.org
dependencies:
  - name: postgresql
    version: 15.x
    condition: postgresql.enabled
    repository: oci://registry-1.docker.io/bitnamicharts
